version: '3.7'
services:
  mongodb_contenedor:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=activities
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 2717:27017